"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "hr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (keyPath: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    sidebar: {
      overview: "Overview",
      devices: "Device Storage",
      gateways: "Gateways",
      ruleEngine: "Rule Engine",
      dataExplorer: "Data Explorer",
      alerts: "Alerts",
      members: "Members",
      apiSettings: "API Settings",
      digitalTwin: "Digital Twin",
      workspace: "Workspace",
      support: "Support",
      account: "Account",
      signOut: "Sign Out Account",
      workspaces: "Workspaces",
      active: "Active",
      addWorkspace: "Add Workspace",
      userManual: "User Manual",
      capabilities: "Platform Capabilities",
      map: "Geographical Map"
    },
    workspace: {
      createTitle: "Create New Workspace",
      createDesc: "Workspaces are isolated environments for your devices, dashboards, and members.",
      nameLabel: "Workspace Name",
      namePlaceholder: "e.g. My Smart Home",
      urlPreview: "URL will be:",
      cancel: "Cancel",
      createBtn: "Create Workspace",
      creatingBtn: "Creating...",
      enterNameError: "Please enter a workspace name",
      successCreate: "Workspace created successfully!",
      failedCreate: "Failed to create workspace"
    },
    header: {
      searchPlaceholder: "Search devices, alerts, rules... (Ctrl+K)",
      helpShortcuts: "Help & Shortcuts",
      helpDesc: "Quick keyboard commands to navigate the platform seamlessly.",
      close: "Close",
      action: "Action",
      key: "Key",
      openSearch: "Open quick search",
      createDashboard: "Create new dashboard",
      toggleHelp: "Toggle help guide",
      developerApps: "Developer Apps",
      devDesc: "Quick launch local Docker environment links.",
      notifications: "Notifications Center",
      markAllRead: "Mark all read",
      unreadNotifications: "unread",
      profile: "Profile Settings",
      currentAccount: "Current Account",
      editProfile: "Edit Profile Settings",
      workspaceSettings: "Workspace Settings",
      signOut: "Sign Out Account",
      fullName: "Full Name",
      email: "Account Email",
      chooseAvatar: "Choose preset avatar",
      saving: "Saving changes...",
      saveChanges: "Save Changes",
      cancel: "Cancel"
    },
    dashboard: {
      overview: "Platform Overview",
      realTime: "Real-time infrastructure monitoring and fleet status",
      exportReport: "Export Report",
      globalSites: "Global Sites",
      activeNodes: "Active Nodes",
      totalDevices: "Total Devices",
      online: "ONLINE",
      activeAlerts: "Active Alerts",
      msgRate: "Message Rate",
      msgDay: "MSG/DAY",
      aggregatedTelemetry: "Aggregated Telemetry",
      networkTraffic: "Network traffic and data ingestion rates",
      systemActivity: "System Activity",
      viewAll: "View All",
      searchDashboards: "Search dashboards...",
      newDashboard: "New Dashboard",
      createDashboardTitle: "Create Dashboard",
      createDashboardDesc: "Deploy a custom-configured dashboards space for fleet visualizers.",
      dashboardName: "Dashboard Name",
      dashboardDesc: "Dashboard Description",
      dashboardDescPlaceholder: "Optional brief description of this dashboards canvas.",
      create: "Create Dashboard",
      widgets: "WIDGETS",
      modified: "Modified",
      noDashboards: "No Dashboards Created",
      noDashboardsDesc: "Build your first dashboards layout to begin visualizing live sensor feeds.",
      createFirst: "Create your first dashboard"
    },
    exporter: {
      title: "Telemetry Report Compiler",
      desc: "Configure your data parameters and compile a customized CSV or JSON export of your device fleet.",
      format: "Report Output Format",
      csv: "CSV Report",
      csvDesc: "Excel / Spreadsheet Compatible",
      json: "JSON Schema",
      jsonDesc: "Developer API Interface",
      timeWindow: "Time Window Scale",
      deviceScope: "Telemetry Device Scope",
      allFleet: "All Fleet Devices",
      cancel: "Cancel",
      compile: "Compile & Download File",
      generating: "Generating Stream...",
      compiling: "Compiling workspace telemetry...",
      querying: "Querying active telemetry indexes...",
      analyzing: "Analyzing device metrics & alerts...",
      structuring: "Structuring final data tables...",
      building: "Building file payload streams..."
    },
    devices: {
      fleetManagement: "Device Management",
      liveSync: "Live Sync",
      desc: "Monitor and configure your deployed devices",
      scanBatch: "Scan Batch",
      provisionDevice: "Provision Device",
      onlineDevices: "Online Devices",
      offlineDevices: "Offline Devices",
      needsAttention: "Needs Attention",
      active: "Active",
      unreachable: "Unreachable",
      warnings: "Warnings",
      searchPlaceholder: "Search by name, EUI, or tag...",
      filters: "Filters",
      sort: "Sort",
      sortNameAsc: "Name (A-Z)",
      sortNameDesc: "Name (Z-A)",
      sortNewestActive: "Newest Active",
      sortOldestActive: "Oldest Active",
      sortBatteryDesc: "Battery Level",
      sortBatteryDescHigh: "Battery Level (High to Low)",
      deviceName: "Device Name",
      status: "Status",
      network: "Network",
      battery: "Battery",
      lastActive: "Last Active",
      actions: "Actions",
      loading: "Loading device data...",
      noDevices: "No devices found matching your search and filter criteria.",
      viewDetails: "View Details",
      configure: "Configure",
      deleteDevice: "Delete Device",
      deleting: "Deleting...",
      brandVendor: "Brand / Vendor",
      connectivity: "Connectivity",
      all: "All",
      clearAll: "Clear All",
      activeFilters: "Active Filters",
      search: "Search",
      brand: "Brand",
      never: "Never",
      ago: "ago",
      statusOnline: "Online",
      statusOffline: "Offline",
      statusWarning: "Warning",
      statusUnknown: "Unknown",
      // Detail page
      dashboard: "Dashboard",
      history: "Telemetry History",
      downlinks: "Downlinks",
      payloadDecoders: "Payload Decoders",
      debug: "Debug",
      liveTelemetry: "Live Telemetry",
      liveTelemetryDesc: "Customizable real-time widget view",
      addWidget: "Add Widget",
      saveLayout: "Save Layout",
      editDashboard: "Edit Dashboard",
      editModeActive: "Edit Mode Active",
      proTip: "Pro Tip",
      proTipDesc: "Grab any widget's top header to drag and reorder. Pull from the bottom corners to resize.",
      noWidgetsTitle: "No Widgets Configured",
      noWidgetsDesc: "Add widgets to visualize the live data streaming from this device.",
      sync: "Sync",
      addDeviceTitle: "Add New Device",
      addDeviceDesc: "Register a new IoT device in your workspace. You can configure fields and payload decoders after creation.",
      deviceNameLabel: "Device Name",
      deviceNamePlaceholder: "e.g. Boiler Room Sensor #1",
      deviceTypeLabel: "Device Type",
      deviceTypeSelectPlaceholder: "Select type",
      connectivityLabel: "Connectivity",
      connectivitySelectPlaceholder: "Select protocol",
      serialLabel: "Serial Number",
      serialPlaceholder: "SN-00001",
      devEuiLabel: "Device EUI",
      appEuiLabel: "App EUI (Join EUI)",
      appKeyLabel: "App Key (Network Key)",
      appKeyDesc: "This key will be sent to ChirpStack but not stored in our database for security.",
      latLabel: "Latitude",
      lngLabel: "Longitude",
      descriptionLabel: "Description",
      descriptionPlaceholder: "Optional device description",
      tagsLabel: "Tags",
      tagsPlaceholder: "temperature, zone-a, critical (comma-separated)",
      tagsDesc: "Separate multiple tags with commas.",
      cancelBtn: "Cancel",
      addDeviceBtn: "Add Device",
      addingBtn: "Adding...",
      successAdd: "Device added successfully",
      successAddDesc: '"{name}" has been registered in your workspace.',
      failedAdd: "Failed to add device",
      loadingDetails: "Loading device details...",
      failedSaveLayout: "Failed to save layout",
      widgetRemoved: "Widget removed",
      failedRemoveWidget: "Failed to remove widget",
      widgetAdded: "Widget added",
      failedAddWidget: "Failed to add widget",
      widgetUpdated: "Widget updated",
      failedUpdateWidget: "Failed to update widget"
    },
    gateways: {
      title: "Gateways",
      desc: "Manage LoRaWAN, MQTT, and custom gateways that relay device data.",
      addGateway: "Add Gateway",
      liveSyncActive: "Live Sync Active",
      lastSeen: "Last Seen",
      loading: "Loading gateways...",
      errorLoading: "Error loading gateways",
      eui: "EUI",
      never: "Never",
      dialogTitle: "Add Gateway",
      dialogDesc: "Register a new gateway to connect your devices to the platform.",
      nameLabel: "Gateway Name",
      namePlaceholder: "Factory North Gateway",
      typeLabel: "Type",
      typePlaceholder: "Select gateway type",
      descLabel: "Description (Optional)",
      descPlaceholder: "Located on the roof of Building A",
      euiLabel: "Gateway EUI (Optional)",
      euiPlaceholder: "e.g. AA0B0C0D0E0F0001",
      euiDesc: "Unique identifier for LoRaWAN gateways.",
      cancel: "Cancel",
      successAdd: "Gateway added successfully",
      failedAdd: "Failed to add gateway"
    },
    gatewayDetails: {
      loading: "Loading gateway...",
      notFound: "Gateway not found",
      liveSync: "Live Sync",
      deleteBtn: "Delete",
      deleteTitle: "Are you absolutely sure?",
      deleteDesc: "This will permanently delete the gateway \"{name}\" and remove it from the LoRaWAN Network Server. Devices connected via this gateway may lose connectivity.",
      cancel: "Cancel",
      deleteConfirmBtn: "Delete Gateway",
      settings: "Settings",
      tabOverview: "Overview",
      tabConfiguration: "Configuration",
      cardStatusTitle: "Gateway Status",
      statusLabel: "Status",
      lastSeenLabel: "Last Seen",
      typeLabel: "Type",
      euiLabel: "EUI",
      uniqueIdLabel: "Unique ID",
      configTitle: "Connection Configuration",
      configDesc: "Configure your gateway to connect to the platform using the following details.",
      protocolLabel: "Protocol",
      protocolDesc: "Ensure your gateway supports this connection method.",
      serverAddressLabel: "Server Address",
      portLabel: "Port",
      instructionsTitle: "Instructions:",
      instruction1: "Log into your gateway's administrative interface.",
      instruction2: "Locate the Packet Forwarder or Basic Station configuration settings.",
      instruction3: "Set the server address exactly to {hostname}",
      instruction4: "Set the port to {port}",
      instruction5: "Ensure your gateway EUI matches {eui}.",
      instruction6: "No ChirpStack setup required: The platform has already provisioned this gateway in the background.",
      successDelete: "Gateway deleted successfully",
      failedDelete: "Failed to delete gateway"
    },
    deviceFields: {
      title: "Custom Fields",
      desc: "Define the data points this device reports. Each field maps to a column in the time-series database.",
      addField: "Add Field",
      noFields: "No fields defined yet.",
      noFieldsDesc: "Add fields to start capturing data from this device.",
      addFirstField: "Add First Field",
      fieldNameHead: "Field Name",
      aliasHead: "Alias",
      typeHead: "Type",
      unitHead: "Unit",
      lastValueHead: "Last Value",
      showOnDashboardHead: "Show on Dashboard",
      editField: "Edit Field",
      editFieldDesc: "Modify this field's configuration.",
      addFieldDesc: "Define a new data field for this device.",
      fieldNameLabel: "Field Name",
      fieldNameHelp: "lowercase, underscores",
      aliasLabel: "Alias / Label",
      colorLabel: "Color",
      showOnDashboardLabel: "Show on device overview dashboard",
      cancel: "Cancel",
      saveChanges: "Save Changes",
      successUpdate: "Field updated",
      successAdd: "Field added",
      failedSave: "Failed to save field",
      successDelete: "Field removed",
      failedDelete: "Failed to delete field",
      failedVisibility: "Failed to update visibility",
      typeNumber: "Number",
      typeString: "String",
      typeLocation: "Location",
      typeJson: "JSON"
    },
    decoders: {
      title: "Live Decoder Debugger",
      desc: "Write JavaScript to translate raw binary payloads into human-readable fields.",
      active: "Active",
      disabled: "Disabled",
      reset: "Reset",
      save: "Save",
      presetsTitle: "Select a preset template to start:",
      jsEditor: "JavaScript Editor",
      unsavedChanges: "Unsaved Changes",
      playgroundTitle: "Live Test Playground",
      hexPayload: "Hex Payload",
      base64Payload: "Base64 Payload",
      payloadInput: "Payload Input",
      spaceSeparated: "Space-separated bytes",
      standardBase64: "Standard Base64 string",
      fPort: "LoRaWAN FPort",
      byteAnalyzer: "Interactive Byte Analyzer",
      byteHelp: "Hover over any byte above to inspect its numerical structures.",
      runTest: "Run Sandbox Test",
      executionError: "Compilation or Execution Error",
      decodedOutput: "Successful Decoded Output",
      telemetryField: "Telemetry Field",
      decodedValue: "Decoded Value",
      type: "Type",
      emptyResult: "Decoder executed successfully but returned an empty object.",
      appliedPreset: "Applied '{name}' preset",
      testSuccess: "Test executed successfully",
      testFailed: "Decoder test failed",
      saveSuccess: "Decoder saved successfully",
      saveFailed: "Failed to save decoder"
    },
    downlinks: {
      scheduleTitle: "Schedule Downlink",
      scheduleDesc: "Send a payload command back to the device.",
      fPort: "LoRaWAN FPort",
      confirmed: "Confirmed",
      payloadFormat: "Payload Format",
      payloadValue: "Payload Value",
      enterHex: "Enter hex bytes...",
      enterBase64: "Enter Base64 encoded payload...",
      enterText: "Enter text command...",
      queueing: "Queueing...",
      queueButton: "Queue Downlink",
      queueTitle: "Downlink Queue",
      queueDesc: "Active and historical downlink commands.",
      total: "total",
      loading: "Loading downlink queue...",
      emptyTitle: "Queue is empty",
      emptyDesc: "No downlinks have been scheduled yet. Use the scheduler form to queue your first command.",
      headScheduled: "Scheduled",
      headFPort: "FPort",
      headType: "Type",
      headPayload: "Payload",
      headStatus: "Status",
      headActions: "Actions",
      badgeConfirmed: "CONFIRMED",
      badgeUnconfirmed: "UNCONFIRMED",
      statusPending: "Pending",
      statusSent: "Sent",
      statusCancelled: "Cancelled",
      actionSimulate: "Simulate",
      sentAt: "Sent at {time}",
      errorEmpty: "Payload cannot be empty",
      errorHexChars: "Hex payload can only contain numbers (0-9) and letters (A-F)",
      errorHexBytes: "Hex payload must have an even number of characters (complete bytes)",
      errorBase64: "Invalid Base64 string",
      errorFPort: "FPort must be between 1 and 223",
      successQueue: "Downlink queued successfully",
      failedQueue: "Failed to queue downlink",
      successCancel: "Downlink cancelled",
      failedCancel: "Failed to cancel downlink",
      successSimulate: "Simulation successful: Downlink sent to device",
      failedSimulate: "Failed to simulate transmission"
    },
    liveLogs: {
      title: "Live Payload Debugger",
      syncing: "Syncing",
      scanning: "Scanning for uplinks...",
      waiting: "Waiting for device join or uplink...",
      rawPayload: "Raw Payload"
    },
    deviceSettings: {
      title: "Device Settings",
      desc: "Configure metadata and connectivity for {name}",
      loading: "Loading settings...",
      generalInfo: "General Information",
      generalInfoDesc: "Basic identification and metadata for your device.",
      deviceName: "Device Name",
      description: "Description",
      descriptionPlaceholder: "Describe the purpose of this device",
      tags: "Tags (comma-separated)",
      tagsPlaceholder: "e.g. zone-1, production, battery-powered",
      connectivityGeo: "Connectivity & Geolocation",
      connectivityGeoDesc: "Technical parameters, protocols, and physical location.",
      connectivityProtocol: "Connectivity Protocol",
      serialNumber: "Serial Number",
      serialNumberPlaceholder: "e.g. SN-000000",
      deviceEui: "Device EUI",
      deviceEuiPlaceholder: "16-character hex string",
      latitude: "Latitude",
      latitudePlaceholder: "e.g. 45.8150",
      longitude: "Longitude",
      longitudePlaceholder: "e.g. 15.9819",
      discardChanges: "Discard Changes",
      saveChanges: "Save Changes",
      saving: "Saving...",
      dangerZone: "Danger Zone",
      dangerZoneDesc: "Once you delete a device, there is no going back. Please be certain.",
      deleteTitle: "Delete this device",
      deleteDesc: "This will permanently delete the device, its measurements, and all associated configuration.",
      deleteBtn: "Delete Device",
      confirmDelete: "Are you sure you want to delete this device? This action cannot be undone.",
      successUpdate: "Device settings updated",
      failedUpdate: "Failed to update device",
      successDelete: "Device deleted",
      failedDelete: "Failed to delete device"
    },
    rules: {
      title: "Rule Engine",
      desc: "Create automated if-this-then-that rules for alerts and actions.",
      totalRules: "Total Rules",
      active: "Active",
      noRulesTitle: "No rules defined for this workspace.",
      loading: "Loading rules engine...",
      confirmDelete: "Are you sure you want to delete this rule?",
      ruleEnabled: "Rule enabled",
      ruleDisabled: "Rule disabled",
      ruleDeleted: "Rule deleted",
      failedToggle: "Failed to toggle rule",
      failedDelete: "Failed to delete rule",
      if: "IF",
      then: "THEN",
      newRule: "New Rule",
      editRule: "Edit Rule",
      createRule: "Create Rule",
      createRuleTitle: "Create New Rule",
      editRuleTitle: "Edit Rule",
      updateRuleDesc: "Update your automation rule settings.",
      createRuleDesc: "Define automation and alerts based on your device data.",
      nameLabel: "Rule Name",
      namePlaceholder: "e.g. High CO2 Alert",
      triggerConditionTitle: "Trigger Condition (IF)",
      deviceLabel: "Device",
      selectDevicePlaceholder: "Select device",
      fieldLabel: "Field",
      selectFieldPlaceholder: "Select field",
      operatorLabel: "Operator",
      valueLabel: "Value",
      valuePlaceholder: "Threshold",
      actionTitle: "Action (THEN)",
      actionTypeLabel: "Action Type",
      targetLabel: "Target",
      targetPlaceholderDefault: "Target identifier",
      cancel: "Cancel",
      saveChanges: "Save Changes",
      validationFillAll: "Please fill in all required fields",
      successUpdate: "Rule updated successfully",
      successCreate: "Rule created successfully",
      failedUpdate: "Failed to update rule",
      failedCreate: "Failed to create rule"
    },
    explorer: {
      title: "Data Explorer",
      desc: "Analyze historical telemetry data and export reports.",
      exportCsv: "Export CSV",
      refresh: "Refresh",
      filtersTitle: "Dataset Filters",
      deviceLabel: "Device",
      selectDevicePlaceholder: "Select device",
      measurementLabel: "Measurement",
      selectFieldPlaceholder: "Select field",
      timeRangeLabel: "Time Range",
      selectRangePlaceholder: "Range",
      lastHour: "Last Hour",
      last6Hours: "Last 6 Hours",
      last24Hours: "Last 24 Hours",
      last7Days: "Last 7 Days",
      last30Days: "Last 30 Days",
      visualizationLabel: "Visualization",
      lineChart: "Line",
      areaChart: "Area",
      noDataTitle: "No Data to Display",
      noDataDesc: "Please select a device and a measurement field from the sidebar.",
      selectFieldToVisualize: "Select a field to visualize",
      historicalTrend: "Historical trend for",
      noDataSelected: "No data selected",
      csvExportSuccess: "CSV exported successfully",
      noDataToExport: "No data to export"
    },
    alerts: {
      title: "Alerts History",
      desc: "Monitor and acknowledge recent system alerts and notifications.",
      clearAll: "Clear All",
      acknowledgeAll: "Acknowledge All",
      searchPlaceholder: "Search alert history...",
      severityHead: "Severity",
      titleHead: "Alert Title",
      messageHead: "Message",
      timeHead: "Time",
      actionsHead: "Actions",
      noAlerts: "No alerts found.",
      loading: "Loading alerts history...",
      alertAcknowledged: "Alert acknowledged",
      failedAcknowledge: "Failed to acknowledge alert",
      noUnacknowledged: "No unacknowledged alerts",
      allAcknowledged: "All alerts acknowledged",
      failedAcknowledgeAll: "Failed to acknowledge all alerts",
      noAlertsToClear: "No alerts to clear",
      confirmClearAll: "Are you sure you want to clear all alerts for this workspace? This action cannot be undone.",
      allCleared: "All alerts cleared",
      failedClearAll: "Failed to clear alerts",
      critical: "Critical",
      warning: "Warning",
      info: "Info"
    },
    members: {
      title: "Members",
      desc: "Manage workspace members and their access roles.",
      inviteMember: "Invite Member",
      inviteToWorkspaceTitle: "Invite to Workspace",
      inviteToWorkspaceDesc: "We'll send an invite link directly to their inbox. Permissions can be assigned after they join.",
      emailLabel: "Email address",
      cancel: "Cancel",
      sendInviteLink: "Send Invite Link",
      sending: "Sending...",
      roles: {
        owner: "Owner",
        admin: "Admin",
        member: "Member",
        viewer: "Viewer"
      },
      rolesPlural: {
        owner: "Owners",
        admin: "Admins",
        member: "Members",
        viewer: "Viewers"
      },
      memberHead: "Member",
      emailHead: "Email",
      roleHead: "Role",
      joinedHead: "Joined",
      loading: "Loading workspace members...",
      promoteTo: "Promote to",
      makeMember: "Make Member",
      makeViewer: "Make Viewer",
      removeFromWorkspace: "Remove from workspace",
      confirmRemove: "Are you sure you want to remove {name} from this workspace?",
      removeSuccess: "has been removed from the workspace",
      roleUpdateSuccess: "Member role updated successfully",
      failedRoleUpdate: "Failed to update member role",
      failedRemove: "Failed to remove member",
      invalidEmail: "Please enter a valid email address",
      inviteSuccess: "Invite dispatched successfully to"
    },
    api: {
      title: "API Settings",
      desc: "Manage your API tokens and service account credentials.",
      createNewToken: "Create New Token",
      accessTokensTitle: "Access Tokens",
      accessTokensDesc: "Use these tokens to authenticate your devices and integrations with our REST API.",
      tokenNameHead: "Token Name",
      keyHead: "Key",
      lastUsedHead: "Last Used",
      createdHead: "Created",
      bestPracticesTitle: "API Best Practices",
      bestPracticesDesc: "Follow these guidelines to keep your workspace secure:",
      practice1: "Never share your tokens in public repositories.",
      practice2: "Rotate your production tokens every 90 days.",
      practice3: "Use separate tokens for each integration (e.g., Gateway 1, Mobile App).",
      practice4: "Revoke tokens immediately if you suspect a leak.",
      exampleCurl: "Example cURL request to ingest data:",
      tokenCopied: "Token copied to clipboard",
      confirmRevoke: "Are you sure you want to revoke this API token? Any applications using it will lose access.",
      tokenRevoked: "API token revoked",
      commandCopied: "Command copied"
    },
    settings: {
      title: "Workspace Settings",
      desc: "Manage your workspace properties, security, and data retention.",
      generalTitle: "General Information",
      generalDesc: "Basic information about this workspace.",
      workspaceNameLabel: "Workspace Name",
      urlSlugLabel: "URL Slug",
      urlSlugDesc: "Changing the slug will change the URL of this workspace.",
      internalIdLabel: "Internal ID (UUID)",
      copyBtn: "Copy",
      saveChangesBtn: "Save Changes",
      securityTitle: "Security & Visibility",
      securityDesc: "Control who can see and access your data.",
      publicWorkspaceLabel: "Public Workspace",
      publicWorkspaceDesc: "Allow anyone with the link to view dashboards.",
      tfaLabel: "Two-Factor Authentication",
      tfaDesc: "Require all members to use 2FA for this workspace.",
      tfaBtn: "Configure Enforced 2FA (Pro)",
      retentionTitle: "Data Retention",
      retentionDesc: "Configure how long telemetry data is stored.",
      historyPeriodLabel: "History Period",
      retentionDescHelp: "Changing retention period may result in permanent deletion of older data.",
      retentionOptions: {
        d7: "7 Days (Free)",
        d30: "30 Days (Standard)",
        y1: "1 Year (Business)",
        infinite: "Indefinite (Enterprise)"
      },
      dangerZoneTitle: "Danger Zone",
      dangerZoneDesc: "Irreversible actions for this workspace.",
      deleteWorkspaceLabel: "Delete Workspace",
      deleteWorkspaceDesc: "Permanently remove this workspace and all associated devices, dashboards and data.",
      deleteWorkspaceBtn: "Delete Workspace",
      loading: "Loading workspace settings...",
      updateSuccess: "Workspace settings updated",
      failedUpdate: "Failed to update settings",
      confirmDelete: "Are you sure you want to delete this workspace? All data, devices, and dashboards will be permanently lost. This action is irreversible.",
      deleteSuccess: "Workspace deleted successfully",
      failedDelete: "Failed to delete workspace",
      idCopied: "ID copied to clipboard"
    }
  },
  hr: {
    sidebar: {
      overview: "Pregled",
      devices: "Spremište uređaja",
      gateways: "Pristupnici",
      ruleEngine: "Sustav pravila",
      dataExplorer: "Istraživač podataka",
      alerts: "Upozorenja",
      members: "Članovi",
      apiSettings: "API Postavke",
      digitalTwin: "Digitalni blizanac",
      workspace: "Radni prostor",
      support: "Podrška",
      account: "Korisnički račun",
      signOut: "Odjava s računa",
      workspaces: "Radni prostori",
      active: "Aktivno",
      addWorkspace: "Dodaj radni prostor",
      userManual: "Korisnički priručnik",
      capabilities: "Mogućnosti platforme",
      map: "Geografska karta"
    },
    workspace: {
      createTitle: "Stvori novi radni prostor",
      createDesc: "Radni prostori su izolirana okruženja za vaše uređaje, nadzorne ploče i članove.",
      nameLabel: "Naziv radnog prostora",
      namePlaceholder: "npr. Moj pametni dom",
      urlPreview: "URL će biti:",
      cancel: "Odustani",
      createBtn: "Stvori radni prostor",
      creatingBtn: "Stvaranje...",
      enterNameError: "Molimo unesite naziv radnog prostora",
      successCreate: "Radni prostor uspješno stvoren!",
      failedCreate: "Neuspješno stvaranje radnog prostora"
    },
    header: {
      searchPlaceholder: "Pretraži uređaje, upozorenja, pravila... (Ctrl+K)",
      helpShortcuts: "Pomoć i prečaci",
      helpDesc: "Brzi prečaci na tipkovnici za lakše kretanje platformom.",
      close: "Zatvori",
      action: "Akcija",
      key: "Tipka",
      openSearch: "Otvori brzu pretragu",
      createDashboard: "Izradi novu nadzornu ploču",
      toggleHelp: "Prikaži / sakrij pomoć",
      developerApps: "Razvojni alati",
      devDesc: "Brze veze za lokalna Docker okruženja.",
      notifications: "Centar za obavijesti",
      markAllRead: "Označi sve pročitano",
      unreadNotifications: "nepročitano",
      profile: "Postavke profila",
      currentAccount: "Trenutni račun",
      editProfile: "Uredi postavke profila",
      workspaceSettings: "Postavke radnog prostora",
      signOut: "Odjavi se s računa",
      fullName: "Ime i prezime",
      email: "E-pošta računa",
      chooseAvatar: "Odaberi profilni avatar",
      saving: "Spremanje promjena...",
      saveChanges: "Spremi promjene",
      cancel: "Odustani"
    },
    dashboard: {
      overview: "Pregled platforme",
      realTime: "Praćenje infrastrukture u stvarnom vremenu i status flote",
      exportReport: "Izvezi izvještaj",
      globalSites: "Lokacije",
      activeNodes: "Aktivni čvorovi",
      totalDevices: "Ukupno uređaja",
      online: "AKTIVNO",
      activeAlerts: "Aktivna upozorenja",
      msgRate: "Brzina poruka",
      msgDay: "PORUKE/DAN",
      aggregatedTelemetry: "Zbrojna telemetrija",
      networkTraffic: "Mrežni promet i brzina unosa podataka",
      systemActivity: "Aktivnosti sustava",
      viewAll: "Prikaži sve",
      searchDashboards: "Pretraži nadzorne ploče...",
      newDashboard: "Nova nadzorna ploča",
      createDashboardTitle: "Izradi nadzornu ploču",
      createDashboardDesc: "Postavite prilagođeni prostor nadzorne ploče za vizualizaciju flote.",
      dashboardName: "Naziv nadzorne ploče",
      dashboardDesc: "Opis nadzorne ploče",
      dashboardDescPlaceholder: "Dodatni kratki opis ove nadzorne ploče.",
      create: "Izradi nadzornu ploču",
      widgets: "METRIKA",
      modified: "Ažurirano",
      noDashboards: "Nema izrađenih nadzornih ploča",
      noDashboardsDesc: "Izradite svoju prvu nadzornu ploču kako biste započeli vizualizaciju senzora.",
      createFirst: "Izradite prvu nadzornu ploču"
    },
    exporter: {
      title: "Sastavljač telemetrijskog izvještaja",
      desc: "Konfigurirajte parametre podataka i sastavite prilagođeni CSV ili JSON izvoz za vašu flotu uređaja.",
      format: "Izlazni format izvještaja",
      csv: "CSV Izvještaj",
      csvDesc: "Kompatibilno s Excelom i tablicama",
      json: "JSON Shema",
      jsonDesc: "Razvojno API sučelje",
      timeWindow: "Vremenski prozor",
      deviceScope: "Obuhvat uređaja",
      allFleet: "Svi uređaji flote",
      cancel: "Odustani",
      compile: "Sastavi i preuzmi datoteku",
      generating: "Generiranje datoteke...",
      compiling: "Sastavljanje telemetrije...",
      querying: "Pretraživanje aktivnih telemetrijskih indeksa...",
      analyzing: "Analiza metrika uređaja i upozorenja...",
      structuring: "Strukturiranje završnih tablica podataka...",
      building: "Izgradnja toka podataka datoteke..."
    },
    devices: {
      fleetManagement: "Upravljanje uređajima",
      liveSync: "Sinkronizacija uživo",
      desc: "Pratite i konfigurirajte svoje instalirane uređaje",
      scanBatch: "Skeniraj seriju",
      provisionDevice: "Registriraj uređaj",
      onlineDevices: "Aktivni uređaji",
      offlineDevices: "Neaktivni uređaji",
      needsAttention: "Potrebna pažnja",
      active: "Aktivno",
      unreachable: "Nedostupno",
      warnings: "Upozorenja",
      searchPlaceholder: "Pretraži po nazivu, EUI-u ili oznaci...",
      filters: "Filtri",
      sort: "Poredaj",
      sortNameAsc: "Naziv (A-Z)",
      sortNameDesc: "Naziv (Z-A)",
      sortNewestActive: "Zadnje aktivno",
      sortOldestActive: "Najstarije aktivno",
      sortBatteryDesc: "Razina baterije",
      sortBatteryDescHigh: "Razina baterije (od veće)",
      deviceName: "Naziv uređaja",
      status: "Status",
      network: "Mreža",
      battery: "Baterija",
      lastActive: "Zadnja aktivnost",
      actions: "Akcije",
      loading: "Učitavanje podataka o uređajima...",
      noDevices: "Nije pronađen nijedan uređaj koji odgovara pretrazi.",
      viewDetails: "Prikaži detalje",
      configure: "Konfiguriraj",
      deleteDevice: "Obriši uređaj",
      deleting: "Brisanje...",
      brandVendor: "Proizvođač / Dobavljač",
      connectivity: "Povezivost",
      all: "Sve",
      clearAll: "Očisti sve",
      activeFilters: "Aktivni filtri",
      search: "Pretraga",
      brand: "Proizvođač",
      never: "Nikada",
      ago: "prije",
      statusOnline: "Na mreži",
      statusOffline: "Izvan mreže",
      statusWarning: "Upozorenje",
      statusUnknown: "Nepoznato",
      // Detail page
      dashboard: "Nadzorna ploča",
      history: "Povijest telemetrije",
      downlinks: "Silazne poruke",
      payloadDecoders: "Dekoderi podataka",
      debug: "Otklanjanje pogrešaka",
      liveTelemetry: "Telemetrija uživo",
      liveTelemetryDesc: "Prilagodljiv prikaz metrike u stvarnom vremenu",
      addWidget: "Dodaj metriku",
      saveLayout: "Spremi raspored",
      editDashboard: "Uredi nadzornu ploču",
      editModeActive: "Uređivanje aktivno",
      proTip: "Savjet",
      proTipDesc: "Uhvatite gornje zaglavlje bilo koje metrike za povlačenje i preslagivanje. Povucite donje kutove za promjenu veličine.",
      noWidgetsTitle: "Nema konfigurirane metrike",
      noWidgetsDesc: "Dodajte metriku za vizualizaciju podataka koji uživo dolaze s ovog uređaja.",
      sync: "Sinkroniziraj",
      addDeviceTitle: "Dodaj novi uređaj",
      addDeviceDesc: "Registrirajte novi IoT uređaj u vašem radnom prostoru. Možete konfigurirati polja i dekodere korisnog tereta nakon kreiranja.",
      deviceNameLabel: "Naziv uređaja",
      deviceNamePlaceholder: "npr. Senzor kotlovnice #1",
      deviceTypeLabel: "Tip uređaja",
      deviceTypeSelectPlaceholder: "Odaberi tip",
      connectivityLabel: "Povezivost",
      connectivitySelectPlaceholder: "Odaberi protokol",
      serialLabel: "Serijski broj",
      serialPlaceholder: "SN-00001",
      devEuiLabel: "Device EUI",
      appEuiLabel: "App EUI (Join EUI)",
      appKeyLabel: "App Key (Mrežni ključ)",
      appKeyDesc: "Ovaj ključ bit će poslan na ChirpStack, ali neće biti pohranjen u našoj bazi podataka radi sigurnosti.",
      latLabel: "Geografska širina",
      lngLabel: "Geografska dužina",
      descriptionLabel: "Opis",
      descriptionPlaceholder: "Opcionalni opis uređaja",
      tagsLabel: "Oznake",
      tagsPlaceholder: "temperatura, zona-a, kritično (odvojeno zarezom)",
      tagsDesc: "Odvojite više oznaka zarezima.",
      cancelBtn: "Odustani",
      addDeviceBtn: "Dodaj uređaj",
      addingBtn: "Dodavanje...",
      successAdd: "Uređaj uspješno dodan",
      successAddDesc: '"{name}" je registriran u vašem radnom prostoru.',
      failedAdd: "Neuspješno dodavanje uređaja",
      loadingDetails: "Učitavanje detalja uređaja...",
      failedSaveLayout: "Neuspješno spremanje rasporeda",
      widgetRemoved: "Metrika uklonjena",
      failedRemoveWidget: "Neuspješno uklanjanje metrike",
      widgetAdded: "Metrika dodana",
      failedAddWidget: "Neuspješno dodavanje metrike",
      widgetUpdated: "Metrika ažurirana",
      failedUpdateWidget: "Neuspješno ažuriranje metrike"
    },
    gateways: {
      title: "Pristupnici",
      desc: "Upravljajte LoRaWAN, MQTT i prilagođenim pristupnicima koji prenose podatke uređaja.",
      addGateway: "Dodaj pristupnik",
      liveSyncActive: "Sinkronizacija uživo aktivna",
      lastSeen: "Zadnja aktivnost",
      loading: "Učitavanje pristupnika...",
      errorLoading: "Greška pri učitavanju pristupnika",
      eui: "EUI",
      never: "Nikada",
      dialogTitle: "Dodaj pristupnik",
      dialogDesc: "Registrirajte novi pristupnik kako biste povezali svoje uređaje na platformu.",
      nameLabel: "Naziv pristupnika",
      namePlaceholder: "Npr. Tvornica Sjever Pristupnik",
      typeLabel: "Tip",
      typePlaceholder: "Odaberite tip pristupnika",
      descLabel: "Opis (Opcionalno)",
      descPlaceholder: "Npr. Nalazi se na krovu zgrade A",
      euiLabel: "EUI Pristupnika (Opcionalno)",
      euiPlaceholder: "npr. AA0B0C0D0E0F0001",
      euiDesc: "Jedinstveni identifikator za LoRaWAN pristupnike.",
      cancel: "Odustani",
      successAdd: "Pristupnik uspješno dodan",
      failedAdd: "Neuspješno dodavanje pristupnika"
    },
    gatewayDetails: {
      loading: "Učitavanje pristupnika...",
      notFound: "Pristupnik nije pronađen",
      liveSync: "Sinkronizacija uživo",
      deleteBtn: "Obriši",
      deleteTitle: "Jeste li potpuno sigurni?",
      deleteDesc: "Ovo će trajno obrisati pristupnik \"{name}\" i ukloniti ga s LoRaWAN mrežnog poslužitelja. Uređaji spojeni preko ovog pristupnika mogu izgubiti vezu.",
      cancel: "Odustani",
      deleteConfirmBtn: "Obriši pristupnik",
      settings: "Postavke",
      tabOverview: "Pregled",
      tabConfiguration: "Konfiguracija",
      cardStatusTitle: "Status pristupnika",
      statusLabel: "Status",
      lastSeenLabel: "Zadnja aktivnost",
      typeLabel: "Tip",
      euiLabel: "EUI",
      uniqueIdLabel: "Jedinstveni ID",
      configTitle: "Konfiguracija veze",
      configDesc: "Konfigurirajte svoj pristupnik za povezivanje na platformu koristeći sljedeće detalje.",
      protocolLabel: "Protokol",
      protocolDesc: "Provjerite podržava li vaš pristupnik ovaj način povezivanja.",
      serverAddressLabel: "Adresa poslužitelja",
      portLabel: "Port",
      instructionsTitle: "Upute:",
      instruction1: "Prijavite se u administrativno sučelje vašeg pristupnika.",
      instruction2: "Pronađite postavke za Packet Forwarder ili Basic Station.",
      instruction3: "Postavite adresu poslužitelja točno na {hostname}",
      instruction4: "Postavite port na {port}",
      instruction5: "Provjerite odgovara li EUI vašeg pristupnika {eui}.",
      instruction6: "Nije potrebno podešavanje na ChirpStacku: Platforma je već osigurala ovaj pristupnik u pozadini.",
      successDelete: "Pristupnik uspješno obrisan",
      failedDelete: "Neuspješno brisanje pristupnika"
    },
    deviceFields: {
      title: "Prilagođena polja",
      desc: "Definirajte podatkovne točke koje ovaj uređaj šalje. Svako polje se mapira u stupac u vremenskoj bazi podataka.",
      addField: "Dodaj polje",
      noFields: "Još nema definiranih polja.",
      noFieldsDesc: "Dodajte polja kako biste započeli prikupljanje podataka s ovog uređaja.",
      addFirstField: "Dodaj prvo polje",
      fieldNameHead: "Naziv polja",
      aliasHead: "Pseudonim",
      typeHead: "Tip",
      unitHead: "Jedinica",
      lastValueHead: "Zadnja vrijednost",
      showOnDashboardHead: "Prikaži na nadzornoj ploči",
      editField: "Uredi polje",
      editFieldDesc: "Izmijenite konfiguraciju ovog polja.",
      addFieldDesc: "Definirajte novo polje podataka za ovaj uređaj.",
      fieldNameLabel: "Naziv polja",
      fieldNameHelp: "mala slova, podvlake",
      aliasLabel: "Pseudonim / Oznaka",
      colorLabel: "Boja",
      showOnDashboardLabel: "Prikaži na preglednoj nadzornoj ploči uređaja",
      cancel: "Odustani",
      saveChanges: "Spremi promjene",
      successUpdate: "Polje ažurirano",
      successAdd: "Polje dodano",
      failedSave: "Neuspješno spremanje polja",
      successDelete: "Polje uklonjeno",
      failedDelete: "Neuspješno brisanje polja",
      failedVisibility: "Neuspješno ažuriranje vidljivosti",
      typeNumber: "Broj",
      typeString: "Tekst",
      typeLocation: "Lokacija",
      typeJson: "JSON"
    },
    decoders: {
      title: "Dekoder podataka uživo",
      desc: "Napišite JavaScript kod kako biste preveli sirove binarne podatke u čitljiva polja.",
      active: "Aktivno",
      disabled: "Onemogućeno",
      reset: "Vrati izvorno",
      save: "Spremi",
      presetsTitle: "Odaberite predložak za početak:",
      jsEditor: "JavaScript uređivač",
      unsavedChanges: "Nespremljene promjene",
      playgroundTitle: "Poligon za testiranje uživo",
      hexPayload: "Hex podaci",
      base64Payload: "Base64 podaci",
      payloadInput: "Sirovi podaci",
      spaceSeparated: "Bajtovi odvojeni razmakom",
      standardBase64: "Standardni Base64 tekst",
      fPort: "LoRaWAN FPort",
      byteAnalyzer: "Interaktivni analizator bajtova",
      byteHelp: "Prijeđite pokazivačem preko bilo kojeg bajta kako biste analizirali njegovu strukturu.",
      runTest: "Pokreni test u pješčaniku",
      executionError: "Greška pri kompajliranju ili izvršavanju",
      decodedOutput: "Uspješno dekodirani izlaz",
      telemetryField: "Telemetrijsko polje",
      decodedValue: "Dekodirana vrijednost",
      type: "Tip",
      emptyResult: "Dekoder se uspješno izvršio ali je vratio prazan objekt.",
      appliedPreset: "Primijenjen predložak '{name}'",
      testSuccess: "Test uspješno izvršen",
      testFailed: "Test dekodera nije uspio",
      saveSuccess: "Dekoder uspješno spremljen",
      saveFailed: "Neuspješno spremanje dekodera"
    },
    downlinks: {
      scheduleTitle: "Zakaži silaznu vezu",
      scheduleDesc: "Pošaljite naredbu s korisnim teretom natrag na uređaj.",
      fPort: "LoRaWAN FPort",
      confirmed: "Potvrđeno",
      payloadFormat: "Format korisnog tereta",
      payloadValue: "Vrijednost korisnog tereta",
      enterHex: "Unesite hex bajtove...",
      enterBase64: "Unesite Base64 kodirane podatke...",
      enterText: "Unesite tekstualnu naredbu...",
      queueing: "U red čekanja...",
      queueButton: "Zakaži silaznu vezu",
      queueTitle: "Red čekanja silaznih veza",
      queueDesc: "Aktivne i povijesne naredbe silazne veze.",
      total: "ukupno",
      loading: "Učitavanje reda čekanja...",
      emptyTitle: "Red čekanja je prazan",
      emptyDesc: "Nema zakazanih silaznih veza. Koristite obrazac za zakazivanje kako biste dodali svoju prvu naredbu.",
      headScheduled: "Zakazano",
      headFPort: "FPort",
      headType: "Tip",
      headPayload: "Podaci",
      headStatus: "Status",
      headActions: "Akcije",
      badgeConfirmed: "POTVRĐENO",
      badgeUnconfirmed: "NEPOTVRĐENO",
      statusPending: "U tijeku",
      statusSent: "Poslano",
      statusCancelled: "Otkazano",
      actionSimulate: "Simuliraj",
      sentAt: "Poslano u {time}",
      errorEmpty: "Korisni teret ne može biti prazan",
      errorHexChars: "Hex podaci mogu sadržavati samo brojeve (0-9) i slova (A-F)",
      errorHexBytes: "Hex podaci moraju imati paran broj znakova (potpuni bajtovi)",
      errorBase64: "Neispravan Base64 tekst",
      errorFPort: "FPort mora biti između 1 i 223",
      successQueue: "Silazna veza uspješno stavljena u red čekanja",
      failedQueue: "Neuspješno stavljanje silazne veze u red čekanja",
      successCancel: "Silazna veza otkazana",
      failedCancel: "Neuspješno otkazivanje silazne veze",
      successSimulate: "Simulacija uspješna: Silazna veza poslana na uređaj",
      failedSimulate: "Neuspješna simulacija prijenosa"
    },
    liveLogs: {
      title: "Analizator sirovih podataka uživo",
      syncing: "Sinkronizacija",
      scanning: "Skeniranje uzlaznih veza...",
      waiting: "Čekanje na pridruživanje uređaja ili uzlaznu vezu...",
      rawPayload: "Sirovi podaci (Payload)"
    },
    deviceSettings: {
      title: "Postavke uređaja",
      desc: "Konfigurirajte metapodatke i povezivost za {name}",
      loading: "Učitavanje postavki...",
      generalInfo: "Opće informacije",
      generalInfoDesc: "Osnovna identifikacija i metapodaci za vaš uređaj.",
      deviceName: "Naziv uređaja",
      description: "Opis",
      descriptionPlaceholder: "Opišite svrhu ovog uređaja",
      tags: "Oznake (odvojene zarezom)",
      tagsPlaceholder: "npr. zona-1, proizvodnja, napajanje-baterijom",
      connectivityGeo: "Povezivost i geolokacija",
      connectivityGeoDesc: "Tehnički parametri, protokoli i fizička lokacija.",
      connectivityProtocol: "Protokol povezivanja",
      serialNumber: "Serijski broj",
      serialNumberPlaceholder: "npr. SN-000000",
      deviceEui: "Device EUI",
      deviceEuiPlaceholder: "16-znamenkasti heksadecimalni niz",
      latitude: "Geografska širina (Latitude)",
      latitudePlaceholder: "npr. 45.8150",
      longitude: "Geografska dužina (Longitude)",
      longitudePlaceholder: "npr. 15.9819",
      discardChanges: "Odbaci promjene",
      saveChanges: "Spremi promjene",
      saving: "Spremanje...",
      dangerZone: "Opasna zona",
      dangerZoneDesc: "Nakon brisanja uređaja nema povratka. Budite sigurni.",
      deleteTitle: "Obriši ovaj uređaj",
      deleteDesc: "Ovo će trajno obrisati uređaj, njegova mjerenja i sve povezane konfiguracije.",
      deleteBtn: "Obriši uređaj",
      confirmDelete: "Jeste li sigurni da želite obrisati ovaj uređaj? Ova radnja se ne može poništiti.",
      successUpdate: "Postavke uređaja su ažurirane",
      failedUpdate: "Neuspješno ažuriranje uređaja",
      successDelete: "Uređaj je obrisan",
      failedDelete: "Neuspješno brisanje uređaja"
    },
    rules: {
      title: "Sustav pravila",
      desc: "Izradite automatizirana pravila tipa 'ako-ovo-onda-ono' za upozorenja i akcije.",
      totalRules: "Ukupno pravila",
      active: "Aktivno",
      noRulesTitle: "Nema definiranih pravila za ovaj radni prostor.",
      loading: "Učitavanje sustava pravila...",
      confirmDelete: "Jeste li sigurni da želite obrisati ovo pravilo?",
      ruleEnabled: "Pravilo omogućeno",
      ruleDisabled: "Pravilo onemogućeno",
      ruleDeleted: "Pravilo obrisano",
      failedToggle: "Neuspješno prebacivanje pravila",
      failedDelete: "Neuspješno brisanje pravila",
      if: "AKO",
      then: "ONDA",
      newRule: "Novo pravilo",
      editRule: "Uredi pravilo",
      createRule: "Stvori pravilo",
      createRuleTitle: "Stvori novo pravilo",
      editRuleTitle: "Uredi pravilo",
      updateRuleDesc: "Ažurirajte postavke vašeg pravila automatizacije.",
      createRuleDesc: "Definirajte automatizaciju i upozorenja na temelju podataka s uređaja.",
      nameLabel: "Naziv pravila",
      namePlaceholder: "npr. Upozorenje na visok CO2",
      triggerConditionTitle: "Uvjet okidanja (IF)",
      deviceLabel: "Uređaj",
      selectDevicePlaceholder: "Odaberite uređaj",
      fieldLabel: "Polje",
      selectFieldPlaceholder: "Odaberite polje",
      operatorLabel: "Operator",
      valueLabel: "Vrijednost",
      valuePlaceholder: "Prag",
      actionTitle: "Akcija (THEN)",
      actionTypeLabel: "Tip akcije",
      targetLabel: "Cilj",
      targetPlaceholderDefault: "Identifikator cilja",
      cancel: "Odustani",
      saveChanges: "Spremi promjene",
      validationFillAll: "Molimo popunite sva obavezna polja",
      successUpdate: "Pravilo uspješno ažurirano",
      successCreate: "Pravilo uspješno stvoreno",
      failedUpdate: "Neuspješno ažuriranje pravila",
      failedCreate: "Neuspješno stvaranje pravila"
    },
    explorer: {
      title: "Istraživač podataka",
      desc: "Analizirajte povijesne podatke telemetrije i izvozite izvještaje.",
      exportCsv: "Izvezi CSV",
      refresh: "Osvježi",
      filtersTitle: "Filtri skupa podataka",
      deviceLabel: "Uređaj",
      selectDevicePlaceholder: "Odaberi uređaj",
      measurementLabel: "Mjerenje",
      selectFieldPlaceholder: "Odaberi polje",
      timeRangeLabel: "Vremenski raspon",
      selectRangePlaceholder: "Raspon",
      lastHour: "Zadnji sat",
      last6Hours: "Zadnjih 6 sati",
      last24Hours: "Zadnjih 24 sata",
      last7Days: "Zadnjih 7 dana",
      last30Days: "Zadnjih 30 dana",
      visualizationLabel: "Vizualizacija",
      lineChart: "Linijski",
      areaChart: "Površinski",
      noDataTitle: "Nema podataka za prikaz",
      noDataDesc: "Molimo odaberite uređaj i mjerno polje u bočnom izborniku.",
      selectFieldToVisualize: "Odaberite polje za vizualizaciju",
      historicalTrend: "Povijesni trend za",
      noDataSelected: "Nema odabranih podataka",
      csvExportSuccess: "CSV uspješno izvezen",
      noDataToExport: "Nema podataka za izvoz"
    },
    alerts: {
      title: "Povijest upozorenja",
      desc: "Pratite i potvrdite nedavna upozorenja i obavijesti sustava.",
      clearAll: "Očisti sve",
      acknowledgeAll: "Potvrdi sve",
      searchPlaceholder: "Pretraži povijest upozorenja...",
      severityHead: "Razina",
      titleHead: "Naslov upozorenja",
      messageHead: "Poruka",
      timeHead: "Vrijeme",
      actionsHead: "Akcije",
      noAlerts: "Nema pronađenih upozorenja.",
      loading: "Učitavanje povijesti upozorenja...",
      alertAcknowledged: "Upozorenje potvrđeno",
      failedAcknowledge: "Neuspješna potvrda upozorenja",
      noUnacknowledged: "Nema nepotvrđenih upozorenja",
      allAcknowledged: "Sva upozorenja potvrđena",
      failedAcknowledgeAll: "Neuspješna potvrda svih upozorenja",
      noAlertsToClear: "Nema upozorenja za čišćenje",
      confirmClearAll: "Jeste li sigurni da želite očistiti sva upozorenja za ovaj radni prostor? Ova radnja se ne može poništiti.",
      allCleared: "Sva upozorenja očišćena",
      failedClearAll: "Neuspješno čišćenje upozorenja",
      critical: "Kritično",
      warning: "Upozorenje",
      info: "Informacija"
    },
    members: {
      title: "Članovi",
      desc: "Upravljajte članovima radnog prostora i njihovim pristupnim ulogama.",
      inviteMember: "Pozovi člana",
      inviteToWorkspaceTitle: "Pozovi u radni prostor",
      inviteToWorkspaceDesc: "Poslat ćemo vezu za pozivnicu izravno u njihovu pristiglu poštu. Dozvole se mogu dodijeliti nakon što se pridruže.",
      emailLabel: "Adresa e-pošte",
      cancel: "Odustani",
      sendInviteLink: "Pošalji pozivnicu",
      sending: "Slanje...",
      roles: {
        owner: "Vlasnik",
        admin: "Administrator",
        member: "Član",
        viewer: "Promatrač"
      },
      rolesPlural: {
        owner: "Vlasnici",
        admin: "Administratori",
        member: "Članovi",
        viewer: "Promatrači"
      },
      memberHead: "Član",
      emailHead: "E-pošta",
      roleHead: "Uloga",
      joinedHead: "Pridružen",
      loading: "Učitavanje članova radnog prostora...",
      promoteTo: "Promoviraj u",
      makeMember: "Učini članom",
      makeViewer: "Učini promatračem",
      removeFromWorkspace: "Ukloni iz radnog prostora",
      confirmRemove: "Jeste li sigurni da želite ukloniti korisnika {name} iz ovog radnog prostora?",
      removeSuccess: "je uklonjen iz radnog prostora",
      roleUpdateSuccess: "Uloga člana uspješno ažurirana",
      failedRoleUpdate: "Neuspješno ažuriranje uloge člana",
      failedRemove: "Neuspješno uklanjanje člana",
      invalidEmail: "Molimo unesite valjanu adresu e-pošte",
      inviteSuccess: "Pozivnica uspješno poslana na"
    },
    api: {
      title: "API Postavke",
      desc: "Upravljajte svojim API tokenima i vjerodajnicama servisnih računa.",
      createNewToken: "Izradi novi token",
      accessTokensTitle: "Pristupni tokeni",
      accessTokensDesc: "Koristite ove tokene za autentifikaciju svojih uređaja i integracija s našim REST API-jem.",
      tokenNameHead: "Naziv tokena",
      keyHead: "Ključ",
      lastUsedHead: "Zadnja uporaba",
      createdHead: "Kreirano",
      bestPracticesTitle: "Najbolje prakse za API",
      bestPracticesDesc: "Slijedite ove smjernice kako biste osigurali svoj radni prostor:",
      practice1: "Nikada ne dijelite svoje tokene u javnim repozitorijima.",
      practice2: "Rotirajte svoje produkcijske tokene svakih 90 dana.",
      practice3: "Koristite zasebne tokene za svaku integraciju (npr. Pristupnik 1, Mobilna aplikacija).",
      practice4: "Odmah opozovite tokene ako sumnjate na curenje.",
      exampleCurl: "Primjer cURL zahtjeva za slanje podataka:",
      tokenCopied: "Token kopiran u međuspremnik",
      confirmRevoke: "Jeste li sigurni da želite opozvati ovaj API token? Sve aplikacije koje ga koriste izgubit će pristup.",
      tokenRevoked: "API token opozvan",
      commandCopied: "Naredba kopirana"
    },
    settings: {
      title: "Postavke radnog prostora",
      desc: "Upravljajte svojstvima radnog prostora, sigurnošću i zadržavanjem podataka.",
      generalTitle: "Opće informacije",
      generalDesc: "Osnovne informacije o ovom radnom prostoru.",
      workspaceNameLabel: "Naziv radnog prostora",
      urlSlugLabel: "URL kratica (Slug)",
      urlSlugDesc: "Promjena URL kratice promijenit će adresu (URL) ovog radnog prostora.",
      internalIdLabel: "Interni ID (UUID)",
      copyBtn: "Kopiraj",
      saveChangesBtn: "Spremi promjene",
      securityTitle: "Sigurnost i vidljivost",
      securityDesc: "Kontrolirajte tko može vidjeti i pristupiti vašim podacima.",
      publicWorkspaceLabel: "Javni radni prostor",
      publicWorkspaceDesc: "Dopustite svima s vezom pregled nadzornih ploča.",
      tfaLabel: "Dvostruka autentifikacija",
      tfaDesc: "Zahtijevaj dvostruku autentifikaciju (2FA) za sve članove ovog radnog prostora.",
      tfaBtn: "Konfiguriraj obavezni 2FA (Pro)",
      retentionTitle: "Zadržavanje podataka",
      retentionDesc: "Konfigurirajte koliko dugo se čuvaju telemetrijski podaci.",
      historyPeriodLabel: "Razdoblje povijesti",
      retentionDescHelp: "Promjena razdoblja zadržavanja može rezultirati trajnim brisanjem starijih podataka.",
      retentionOptions: {
        d7: "7 dana (Besplatno)",
        d30: "30 dana (Standardno)",
        y1: "1 godina (Poslovno)",
        infinite: "Neograničeno (Enterprise)"
      },
      dangerZoneTitle: "Opasna zona",
      dangerZoneDesc: "Nepovratne radnje za ovaj radni prostor.",
      deleteWorkspaceLabel: "Obriši radni prostor",
      deleteWorkspaceDesc: "Trajno uklonite ovaj radni prostor i sve povezane uređaje, nadzorne ploče i podatke.",
      deleteWorkspaceBtn: "Obriši radni prostor",
      loading: "Učitavanje postavki radnog prostora...",
      updateSuccess: "Postavke radnog prostora ažurirane",
      failedUpdate: "Neuspješno ažuriranje postavki",
      confirmDelete: "Jeste li sigurni da želite obrisati ovaj radni prostor? Svi podaci, uređaji i nadzorne ploče bit će trajno izgubljeni. Ova radnja je nepovratna.",
      deleteSuccess: "Radni prostor uspješno obrisan",
      failedDelete: "Neuspješno brisanje radnog prostora",
      idCopied: "ID kopiran u međuspremnik"
    }
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLanguage = localStorage.getItem("platform-lang") as Language;
    if (savedLanguage === "en" || savedLanguage === "hr") {
      setLanguageState(savedLanguage);
    }
    setMounted(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("platform-lang", lang);
  };

  const t = (keyPath: string): string => {
    if (!mounted) return keyPath.split(".").pop() || keyPath;
    
    const keys = keyPath.split(".");
    let current: any = translations[language];
    
    for (const key of keys) {
      if (current && current[key] !== undefined) {
        current = current[key];
      } else {
        // Fallback to English lookup if key missing in Croatian
        let engCurrent: any = translations.en;
        for (const engKey of keys) {
          if (engCurrent && engCurrent[engKey] !== undefined) {
            engCurrent = engCurrent[engKey];
          } else {
            return keys.pop() || keyPath;
          }
        }
        return typeof engCurrent === "string" ? engCurrent : (keys.pop() || keyPath);
      }
    }
    
    return typeof current === "string" ? current : (keys.pop() || keyPath);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
