-- Disable RLS for local development UI testing

ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspaces DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.fields DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payload_decoders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.measurements DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboards DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.widgets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.gateways DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts DISABLE ROW LEVEL SECURITY;
